### ISSUE TITLE
"value_distance_interval" is not used in app.

### ISSUE THREAD

**Issue by alogblog** [asamm/locus-map-tts-commands#2]
The value of the key "**value_distance_interval**" (eg. "Lap distance %D1" in en.tts) is not used in Locus Map app's audio coach.

For example, if I modified that value into "Lap distance this is a little bug %D1", the result audio was the same like "Lap distance %D1".

Of course, in most languages case, the words of "Lap distance(in apps resources file)" and "Lap distance(in user's tts file) %D1" might be the same. So most users couldn't catch it.

Thanks.

**Comment by menion** [comment]
Hello,
thanks for the bug report. I'm anyway unable to simulate this problem.

I take the original "EN" file from this repo, modified `value_distance_interval` value, and set audio coach based on the current screen:
![image](https://user-images.githubusercontent.com/1257075/106953946-57440280-6733-11eb-9e9c-d825f44a3356.png)

And this setup works correctly. May you write to me about the difference of your setup? Thanks.

**Comment by alogblog** [comment]
I recorded my testing, but too large(~100M) to upload it in github(10M). so I uploaded it in google drive.

https://drive.google.com/file/d/1nzRxeZpEvvSiYZ9RXcJQOQdMpccidneC/view?usp=sharing


Phone: Android 11, Galaxy S10+
In my video, some settings are,
Recording profiles: 1m/1s/100m, (Distance OR time)
Audio coach: Time interval 10s

**Comment by menion** [comment]
Thanks for the nice video and also for using the Czech language :).
The Czech read at the start of the video does not match the content in the file. Do you have your "cs.tts" and also "ko.tts" files in **Locus/data/tts** directory? Also, changes in TTS files when the app already uses them should have no effect as the content is loaded & cached.

I've double-checked settings on my device and it simply works correctly. You may also try to send me your modified TTS file you use in Locus/data/tts directory so I may test it with it.

**Comment by alogblog** [comment]
Those files are from this github...
https://drive.google.com/file/d/1vRMTfCsZMi80Jno4TTLe44m3bO8TfVuG/view?usp=sharing


Right. If we modified tts file, then we should restart the app. It's the way I used in testing. But, in this video, I used quick method by switching TTS engine because of short filming. In my exprience, the results was same.

In my video, before switching TTS (lang) engine, I modified cs.tts's two keywords(value_distance_interval and value_distance_track) values.
But "value_distance_track" was applied(I could hear x x x things) but the other was not, as you see in video.

I had the same results in ko/ja/en/cs.tts files.

My doubts is, why does that keyword only cause a different result...

**Comment by menion** [comment]
Ah, I've got it. Give it a try and take a small walk about your house to test it :).

In the app, when the distance is equal to 0, the TTS generator returns empty text. But later, when text should be spoken by the TTS engine, this text is "repaired" by internal translated text to "Lap distance" value.

I've never noticed this problem because I've never tested it only based on spend time without any distances.

Thanks, I'll fix this in the Locus Map to the next version. Let me know when during movement, all is ok ...
