### ISSUE TITLE
Temperatue/Humidity value resolution

### ISSUE THREAD

**Issue by alogblog** [asamm/locus-map-tts-commands#4]
"value_humidity_current": "humidity %V1",
"value_temperature_current": "temperature %V1",

In WS07 BT thermometer, I found the two sensor values are represented into 1/1000 (degree/percent) resoultion.

For example, audio coach says "Temperature 24.567", which is I think too cumbersome.

How about if V1 is XX.X, V2 is XX.XX, V0 is XX with rounding off. Or if its too complex, just only V1 is XX.X.
I think it might apply to all other external sensor's values.

Please consider my idea.

Thanks.

**Comment by menion** [comment]
Ah my bad. Thanks, will be fixed in the next app version!
