### ISSUE TITLE
ro.tts

### ISSUE THREAD

**Issue by eduard5557** [asamm/locus-map-tts-commands#7]
Hi, 

I translated en.tts taken from here in Romanian.
I tested it in Locus/data/tts and works as expected.

I uploaded ro.tts

Thanks,
[ro.tts.zip](https://github.com/asamm/locus-map-tts-commands/files/8465971/ro.tts.zip)

Razvan

**Comment by menion** [comment]
Thank you very much! Translation will be added into next app version.
